site_name: "Documentation n8n - Tunisian 🇹🇳"
site_url: "https://louatizine.github.io/Document/"
use_directory_urls: true

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Basculer en mode sombre
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Basculer en mode clair
  font:
    text: Roboto
    code: Fira Code
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

docs_dir: docs
site_dir: site

nav:
  - Accueil: index.md
  - Introduction: introduction.md
  - Premiers pas: getting-started.md
  - Installation: installation.md
  - Premier Workflow: first-workflow.md
  - Exemples: examples.md
  - Ressources: resources.md

plugins:
  - search
  - macros

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - 'assets/css/custom.css'

extra_javascript:
  - 'assets/js/custom.js'
