site_name: "Documentation n8n - Tunisian 🇹🇳"
site_url: "https://username.github.io/repo-name/"
use_directory_urls: true

theme:
  name: material
  palette:
    primary: 'blue'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Fira Code'
  logo: 'assets/images/logo.png'
  favicon: 'assets/images/favicon.ico'
  features:
    - navigation.tabs          # enables top navbar tabs
    - navigation.sections      # ensures sidebar & navbar sync
    - instant
    - content.code.copy
    - content.code.annotate

docs_dir: docs
site_dir: site

nav:
  - Accueil: index.md
  - Introduction: introduction.md
  - Premiers pas: getting-started.md
  - Installation: installation.md
  - Premier Workflow: first-workflow.md
  - Exemples: examples.md
  - Ressources: resources.md

plugins:
  - search
  - macros

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc
  - pymdownx.tilde

extra_css:
  - 'assets/css/custom.css'

extra_javascript:
  - 'assets/js/custom.js'
