site_name: "Documentation n8n - Tunisian"
site_url: "http://localhost:8000"
theme:
  name: material
  palette:
    primary: 'blue'
    accent: 'light blue'
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Getting Started: getting-started.md
  - Installation: installation.md
  - First Workflow: first-workflow.md
  - Examples: examples.md
  - Table: table.md
  - Resources: resources.md

docs_dir: docs
site_dir: site
